### ISSUE TITLE
The 7B LoRA downloads the 13B foundational model instead of the 7B one

### ISSUE THREAD

**Issue by Belluxx** [serp-ai/LLaMA-8bit-LoRA#1]
Why does the LoRA `serpdotai/llama-hh-lora-7B` config file point to `decapoda-research/llama-13b-hf` instead of `decapoda-research/llama-7b-hf`?

**Comment by francislabountyjr** [comment]
I used a local version of the model so I put in the HuggingFace model_ids for compatibility. It's fixed, thank you for pointing that out!
