### ISSUE TITLE
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported. After 7B foundational model download.

### ISSUE THREAD

**Issue by Belluxx** [serp-ai/LLaMA-8bit-LoRA#2]
After the download of the 7B foundational model, the `merge_adapter_weights.py` script crashes with the error `Tokenizer class LLaMATokenizer does not exist or is not currently imported`.

I [found](https://github.com/huggingface/transformers/issues/22222#issuecomment-1473423183) that the tokenizer class should be `LlamaTokenizer` instead of `LLaMATokenizer`.

```
Traceback (most recent call last):
  File "/Users/.../LLaMA-8bit-LoRA/merge_adapter_weights.py", line 35, in <module>
    tokenizer = AutoTokenizer.from_pretrained(peft_config.base_model_name_or_path)
  File "/Users/.../venv/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 677, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
```

**Comment by francislabountyjr** [comment]
Are you using transformers 4.28? You may have to install it from the repo using the command `pip install git+https://github.com/huggingface/transformers` and if that does not work let me know and I can try replacing the Auto classes with the Llama classes

**Comment by Belluxx** [comment]
@francislabountyjr Yes i installed transformers with that command, and pytorch 2.0.0 stable instead of the nightly one, but i get the same error.

This is my packages configuration:
```
Package            Version
------------------ -----------
accelerate         0.17.1
certifi            2022.12.7
charset-normalizer 3.1.0
filelock           3.10.0
huggingface-hub    0.13.3
idna               3.4
Jinja2             3.1.2
MarkupSafe         2.1.2
mpmath             1.3.0
networkx           3.0
numpy              1.24.2
packaging          23.0
peft               0.2.0
pip                23.0.1
psutil             5.9.4
PyYAML             6.0
regex              2022.10.31
requests           2.28.2
setuptools         63.2.0
sympy              1.11.1
tokenizers         0.13.2
torch              2.0.0
tqdm               4.65.0
transformers       4.28.0.dev0
typing_extensions  4.5.0
urllib3            1.26.15
```

**Comment by francislabountyjr** [comment]
Okay, I changed all auto model and tokenizer calls with the equivalent Llama classes. Can you pull the latest version of the repo and give it a try and let me know if that fixes things for you?

**Comment by Belluxx** [comment]
@francislabountyjr now it works perfectly.

The script printed this (i'll leave it just for info)
```
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
```

Also in the `llama-7B-hh-adapter-merged` directory i got two different model files:

- `pytorch_model-00001-of-00002.bin`
- `pytorch_model-00002-of-00002.bin`
- `pytorch_model.bin.index.json` that points every layer to the respective bin file that contains it (part 1 or part 2)

<a href="https://imgbb.com/"><img src="https://i.ibb.co/9pfGbQP/a.png" alt="a" border="0" width=300></a>

Is this expected? I modified the script by changing the last line to `model.save_pretrained(script_args.output_dir, max_shard_size="32GB")` so that the model bin file doesn't get split in two parts.

<a href="https://ibb.co/Z8xKkV5"><img src="https://i.ibb.co/zRZb0rp/Screenshot-2023-03-23-at-13-39-23.png" alt="Screenshot-2023-03-23-at-13-39-23" width=500 border="0"></a>

**Comment by francislabountyjr** [comment]
When it saves the pretrained it should just save the lora weights, which is usually a relatively small file. And sorry for the late repsonse!
