### ISSUE TITLE
I see you using a tool-following approach on gpt-3.5 to generate a dataset for the Lora training, would you be willing to put your weights up somewhere?

### ISSUE THREAD

**Issue by factoidforrest** [serp-ai/LLaMA-8bit-LoRA#4]
This happens to be the _exact_ problem I can here trying to solve and it seems like you've already been at it. 

This is very cool. Would you happen to be willing to share the Lora weights that you've trained based on that? Perhaps they are already up somewhere. Maybe you already have some stuff on HuggingFace. Could be cool to link to from the readme.

By the way, using the Lora approach is just great. It avoids the licensing problems very deftly, and its just a more efficient and hot-swappable way to go. Really impressed.

**Comment by francislabountyjr** [comment]
Haven't had the chance to train a tool following LLaMA yet, hopefully soon though!
